### ISSUE TITLE
Slack Variables for Branch Flow Constraints

### ISSUE THREAD

**Issue by LFPower** [Breakthrough-Energy/REISE.jl#128]
https://github.com/Breakthrough-Energy/REISE.jl/blob/d78ee1f18d85480ec52fae8a0e5a6a86902ac960/src/model.jl#L345

It is suggested that we add the slack variables for branch flow limits constrains.  In industry practice, branch flow limits are soft constraints which can be relaxed in day-ahead unit commitment.

**Comment by danielolsen** [comment]
The `_build_model` function will soften the branch flow constraints if the `trans_viol_enabled` parameter is set to `true`. By default it is `false`, but the `interval_loop` function takes a `model_kwargs` dict which can contain overrides which are passed to `_build_model`. However, there is not currently a way to specify that this should be the case from the main user-facing `run_scenario` function.

**Comment by LFPower** [comment]
> The `_build_model` function will soften the branch flow constraints if the `trans_viol_enabled` parameter is set to `true`. By default it is `false`, but the `interval_loop` function takes a `model_kwargs` dict which can contain overrides which are passed to `_build_model`. However, there is not currently a way to specify that this should be the case from the main user-facing `run_scenario` function.

Thanks.  I turn on the trans_viol_enabled flag and find a bug. Please see the fixed one as follows:

        JuMP.@expression(m, branch_limit_pmin[br in sets.branch_idx, h in hour_idx], branch_pmin[br] - trans_viol[br,h])
        JuMP.@expression(m, branch_limit_pmax[br in sets.branch_idx, h in hour_idx], branch_pmax[br] + trans_viol[br,h])

**Comment by danielolsen** [comment]
There is a test branch that I was working on which not only aimed to fix this indexing issue, but also to save the results, see `daniel/save_trans_viol`. If this is something you need quickly, maybe working with that branch could help.
