### ISSUE TITLE
Error when launching a simulation in container

### ISSUE THREAD

**Issue by jon-hagg** [Breakthrough-Energy/REISE.jl#129]
I get this stack trace when launching a simulation using the demo script in plug. 

```
'File case_storage.mat not found in /mnt/bes/pcm/tmp/scenario_1',
  'Demand flexibility profiles not found in /mnt/bes/pcm/tmp/scenario_1',
  'Julia exception: UndefKeywordError: keyword argument duration not assigned',
  'Stacktrace:',
  '[1] read_demand_flexibility(::String) at /app/src/read.jl:178',
  '[2] run_scenario(; num_segments::Int64, interval::Int64, n_interval::Int64, start_index::Int64, inputfolder::String, outputfolder::String, threads::Nothing, optimizer_factory::Type{T} where T, solver_kwargs::Nothing) at /app/src/REISE.jl:64',
```

**Comment by danielolsen** [comment]
Oops. This probably came from https://github.com/Breakthrough-Energy/REISE.jl/pull/118.

**Comment by lanesmith** [comment]
Whoops, I'm working to address this right now.

**Comment by BainanXia** [comment]
It's here: https://github.com/Breakthrough-Energy/REISE.jl/blob/f192da66d87c61d7e2c1fd9c1d8af5a3886873e7/src/read.jl#L105 Another csv is needed as inputs based on the latest PR @danielolsen mentioned above. `PowerSimData` hasn't been updated to support the latest demand flexibility feature yet as discussed with @lanesmith before the above PR is merged.

**Comment by lanesmith** [comment]
> It's here:
> 
> https://github.com/Breakthrough-Energy/REISE.jl/blob/f192da66d87c61d7e2c1fd9c1d8af5a3886873e7/src/read.jl#L105
> 
> Another csv is needed as inputs based on the latest PR @danielolsen mentioned above. `PowerSimData` hasn't been updated to support the latest demand flexibility feature yet as discussed with @lanesmith before the above PR is merged.

There is a problem on the `REISE.jl` side. If a file is not provided, not all of the parameters in the `DemandFlexibility` are assigned. I thought that not all parameters need to be assigned, but I was wrong. There may still be problems on the `PowerSimData` side, but the error that @jon-hagg posted above matches with the `REISE.jl` error I just found. I'm making the REISE.jl fix right now and should be able to get a PR submitted soon.
