### ISSUE TITLE
Increase the Granularity of Demand Flexibility Input File

### ISSUE THREAD

**Issue by dongqi-wu** [Breakthrough-Energy/REISE.jl#140]
# :rocket:

- [x] Is your feature request essential for your project?

### Describe the workflow you want to enable
I wish to increase the data granularity of the input file `demand_flexibility.csv`. The current input assigns a number per load-zone which get later converted and applied to all load buses in the that load-zone in the opt problem formulation. This implies all loads in each load-zone have the same flexibility which is not a very realistic representation flexible demand behaviour.  I suggest instead of assigning ONE number to all buses in a load-zone, the user should be able to specify the flexibility of each load bus individually.

### Describe your proposed implementation
This should provide a description of the feature request, e.g.:
* The dimension of input file `demand_flexibility.csv` should be (hour_num, load_bus_num) instead of (hour_num, load_zone_num)
* The function `_make_bus_demand_flexibility_amount` should be adjusted appropriately such that it selects a partition of `demand_flexibility.flex_amt` that corresponds to the interval of the model, instead of creating a matrix using the function `permutedims()`.

### Describe alternatives you've considered, if relevant
An alternative or improved implementation is proposed in issue #141

**Comment by lanesmith** [comment]
I agree that this is useful functionality (eventually demand flexibility was going to need to be specified at the bus level for our feature reduction implementation, so this is a nice first step), though I don't necessarily think we should get rid of the demand-flexibility-by-load-zone option. As was discussed in Tuesday's meeting, there is likely a way that we can keep the load-zone-level granularity while also introducing the bus-level granularity. It seems that issue #141 discusses a route where both types of inputs can coexist, so I am more in favor of the type of solution presented in that issue.
