### ISSUE TITLE
Refactor REISE.jl to comply with a standard style guide

### ISSUE THREAD

**Issue by lanesmith** [Breakthrough-Energy/REISE.jl#152]
# :rocket:

- [ ] Is your feature request essential for your project?

### Describe the workflow you want to enable
There would be no change to how users interact with `REISE.jl` or how `REISE.jl` functions.

### Describe your proposed implementation
Refactor the modules of `REISE.jl` to follow a single standard style guide. In the past, we have discussed following the [Blue](https://github.com/invenia/BlueStyle#documentation) style guide.

**Comment by danielolsen** [comment]
We should probably also add an automated workflow to check compliance for new code, like we do for `black`.

**Comment by rouille** [comment]
You can also create a **docs** folder enclosing the details of the model (equations, etc.) that would be written in ReST (great for LaTeX!) and have a more succinct README as we have for **PowerSimData**.
